In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from astropy.io import fits
from astropy.table import Table, vstack
from astropy.coordinates import SkyCoord
from astroquery.sdss import SDSS
from astropy.table import Table, vstack
import astropy.units as u
from astroquery.simbad import Simbad, conf
from multiprocessing import Pool
from functools import partial

Simbad.SIMBAD_URL
# Simbad.SIMBAD_URL = 'http://simbad.cfa.harvard.edu/simbad/sim-script'

/home/benlowe/.local/lib/python3.9/site-packages/setuptools_scm/_integration/setuptools.py:31: RuntimeWarning:
ERROR: setuptools==53.0.0 is used in combination with setuptools_scm>=8.x

Your build configuration is incomplete and previously worked by accident!
setuptools_scm requires setuptools>=61

Suggested workaround if applicable:
 - migrating from the deprecated setup_requires mechanism to pep517/518
   and using a pyproject.toml to declare build dependencies
   which are reliably pre-installed before running the build tools

  warnings.warn(

'https://simbad.cds.unistra.fr/simbad/sim-script'

In [1]:
148 - 25

123

In [12]:
Simbad.SIMBAD_URL = "http://simbad.cfa.harvard.edu/simbad/sim-script"

# Verify it
print(f"Target URL: {Simbad.SIMBAD_URL}")

# Run query
try:
    result = Simbad.query_object("BPS BS 16545-089")
    print(result)
except Exception as e:
    print(f"Still failing: {e}")

Target URL: http://simbad.cfa.harvard.edu/simbad/sim-script
None

In [26]:
sarah = pd.read_csv('/data/misfit/benlowe/xshooter/p115/sarah/Fe_combined_abundances_weighted_shift7.csv')
sarah_stars = sarah['star'].tolist()

sarah_hds = []
for star in sarah_stars:
    print(f"Querying Simbad for star: {star}")
    Simbad.add_votable_fields('ids')

    if star.startswith('HD-'):
        star = star.replace('HD-', 'HD ')
    
    try:
        ids = Simbad.query_object(star)[0]
    except TypeError:
        print(f"Failed to query Simbad for star: {star}")
        continue
    
    try:
        hd_ids = [s for s in str(ids['IDS']).split('|') if 'HD ' in s][0]
    except IndexError:
         print(f"No HD ID found for star: {star}")
         continue
    print(hd_ids)
    star_dict = {'star': star, 'hd_id': hd_ids}
    sarah_hds.append(star_dict)

Querying Simbad for star: 11_Lib
HD 130952
Querying Simbad for star: 18 Del
HD 199665
Querying Simbad for star: 1RXS-J090911.4-122130

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): '1RXS-J090911.4-122130' this identifier has an incorrect format for catalog: 	1RXS : 1st ROSAT X Survey [astroquery.simbad.core]

Failed to query Simbad for star: 1RXS-J090911.4-122130
Querying Simbad for star: 20_Mon
HD  54810
Querying Simbad for star: 27_Mon
HD  65695
Querying Simbad for star: 39_Hya
HD  85444
Querying Simbad for star: 81 Cet
HD  16400
Querying Simbad for star: AO_For
HD  17025
Querying Simbad for star: Arcturus
HD 124897
Querying Simbad for star: C14_2829

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'C14 2829' this identifier has an incorrect format for catalog: 	C : Cluster [astroquery.simbad.core]

Failed to query Simbad for star: C14_2829
Querying Simbad for star: CD-2412897
No HD ID found for star: CD-2412897
Querying Simbad for star: CD-662318
No HD ID found for star: CD-662318
Querying Simbad for star: E60

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'E60' this identifier has an incorrect format for catalog: 	1E : catalogue 1E [astroquery.simbad.core]

Failed to query Simbad for star: E60
Querying Simbad for star: E98

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'E98' this identifier has an incorrect format for catalog: 	1E : catalogue 1E [astroquery.simbad.core]

Failed to query Simbad for star: E98
Querying Simbad for star: EPIC211333233
No HD ID found for star: EPIC211333233
Querying Simbad for star: HD  96445
HD  96445
Querying Simbad for star: HD 211420
HD 211420
Querying Simbad for star: HD-10042
HD  10042
Querying Simbad for star: HD-101021
HD 101021
Querying Simbad for star: HD-103462
HD 103462
Querying Simbad for star: HD-104555
HD 104555
Querying Simbad for star: HD-10615
HD  10615
Querying Simbad for star: HD-107567
HD 107567
Querying Simbad for star: HD-10761
HD  10761
Querying Simbad for star: HD-107815
HD 107815
Querying Simbad for star: HD-109379
HD 109379
Querying Simbad for star: HD-11025
HD  11025
Querying Simbad for star: HD-110666
HD 110666
Querying Simbad for star: HD-111295
HD 111295
Querying Simbad for star: HD-111315
HD 111315
Querying Simbad for star: HD-111884
HD 111884
Querying Simbad for star: HD-111915
HD 111915
Querying Simbad for star: HD-113226
HD 113226
Querying Simbad for star: HD-11332
HD  11332
Querying Simbad for star: HD-115478
HD 115478
Querying Simbad for star: HD-116244
HD 116244
Querying Simbad for star: HD-11977
HD  11977
Querying Simbad for star: HD-121416
HD 121416
Querying Simbad for star: HD-122430
HD 122430
Querying Simbad for star: HD-12270
HD  12270
Querying Simbad for star: HD-123123
HD 123123
Querying Simbad for star: HD-124206
HD 124206
Querying Simbad for star: HD-12431
HD  12431
Querying Simbad for star: HD-12438
HD  12438
Querying Simbad for star: HD-124882
HD 124882
Querying Simbad for star: HD-125560
HD 125560
Querying Simbad for star: HD-12583
HD  12583
Querying Simbad for star: HD-129456
HD 129456
Querying Simbad for star: HD-129893
HD 129893
Querying Simbad for star: HD-130259
HD 130259
Querying Simbad for star: HD-130650
HD 130650
Querying Simbad for star: HD-13263
HD  13263
Querying Simbad for star: HD-132905
HD 132905
Querying Simbad for star: HD-133631
HD 133631
Querying Simbad for star: HD-13423
HD  13423
Querying Simbad for star: HD-134505
HD 134505
Querying Simbad for star: HD-136014
HD 136014
Querying Simbad for star: HD-13692
HD  13692
Querying Simbad for star: HD-13940
HD  13940
Querying Simbad for star: HD-139521
HD 139521
Querying Simbad for star: HD-139980
HD 139980
Querying Simbad for star: HD-140861
HD 140861
Querying Simbad for star: HD-143546
HD 143546
Querying Simbad for star: HD-144608
HD 144608
Querying Simbad for star: HD-146690
HD 146690
Querying Simbad for star: HD-14703
HD  14703
Querying Simbad for star: HD-14830
HD  14830
Querying Simbad for star: HD-14832
HD  14832
Querying Simbad for star: HD-148890
HD 148890
Querying Simbad for star: HD-1522
HD   1522
Querying Simbad for star: HD-156854
HD 156854
Querying Simbad for star: HD-157527
HD 157527
Querying Simbad for star: HD-159194
HD 159194
Querying Simbad for star: HD-161814
HD 161814
Querying Simbad for star: HD-162049
HD 162049
Querying Simbad for star: HD-163145
HD 163145
Querying Simbad for star: HD-163652
HD 163652
Querying Simbad for star: HD-165135
HD 165135
Querying Simbad for star: HD-16522
HD  16522
Querying Simbad for star: HD-165760
HD 165760
Querying Simbad for star: HD-166063
HD 166063
Querying Simbad for star: HD-166599
HD 166599
Querying Simbad for star: HD-16815
HD  16815
Querying Simbad for star: HD-169370
HD 169370
Querying Simbad for star: HD-16975
HD  16975
Querying Simbad for star: HD-169836
HD 169836
Querying Simbad for star: HD-171759
HD 171759
Querying Simbad for star: HD-172211
HD 172211
Querying Simbad for star: HD-17374
HD  17374
Querying Simbad for star: HD-1737
HD   1737
Querying Simbad for star: HD-174295
HD 174295
Querying Simbad for star: HD-175219
HD 175219
Querying Simbad for star: HD-175401
HD 175401
Querying Simbad for star: HD-17793
HD  17793
Querying Simbad for star: HD-17824
HD  17824
Querying Simbad for star: HD-179443
HD 179443
Querying Simbad for star: HD-181517
HD 181517
Querying Simbad for star: HD-182893
HD 182893
Querying Simbad for star: HD-18293
HD  18293
Querying Simbad for star: HD-18322
HD  18322
Querying Simbad for star: HD-188114
HD 188114
Querying Simbad for star: HD-18885
HD  18885
Querying Simbad for star: HD-189005
HD 189005
Querying Simbad for star: HD-190056
HD 190056
Querying Simbad for star: HD-192947
HD 192947
Querying Simbad for star: HD-193721
HD 193721
Querying Simbad for star: HD-196171
HD 196171
Querying Simbad for star: HD-198232
HD 198232
Querying Simbad for star: HD-199951
HD 199951
Querying Simbad for star: HD-20037
HD  20037
Querying Simbad for star: HD-200763
HD 200763
Querying Simbad for star: HD-201381
HD 201381
Querying Simbad for star: HD-201852
HD 201852
Querying Simbad for star: HD-204381
HD 204381
Querying Simbad for star: HD-20894
HD  20894
Querying Simbad for star: HD-21011
HD  21011
Querying Simbad for star: HD-21430
HD  21430
Querying Simbad for star: HD-220009
HD 220009
Querying Simbad for star: HD-22231
HD  22231
Querying Simbad for star: HD-22409
HD  22409
Querying Simbad for star: HD-225197
HD 225197
Querying Simbad for star: HD-22663
HD  22663
Querying Simbad for star: HD-22676
HD  22676
Querying Simbad for star: HD-23319
HD  23319A
Querying Simbad for star: HD-23719
HD  23719
Querying Simbad for star: HD-23940
HD  23940
Querying Simbad for star: HD-24160
HD  24160
Querying Simbad for star: HD-24706
HD  24706
Querying Simbad for star: HD-2529
HD   2529
Querying Simbad for star: HD-26967
HD  26967
Querying Simbad for star: HD-27256
HD  27256
Querying Simbad for star: HD-28028
HD  28028
Querying Simbad for star: HD-28093
HD  28093
Querying Simbad for star: HD-29291
HD  29291
Querying Simbad for star: HD-29737
HD  29737
Querying Simbad for star: HD-29751
HD  29751
Querying Simbad for star: HD-30185
HD  30185
Querying Simbad for star: HD-30814
HD  30814
Querying Simbad for star: HD-31414
HD  31414
Querying Simbad for star: HD-32453
HD  32453
Querying Simbad for star: HD-32515
HD  32515
Querying Simbad for star: HD-34172
HD  34172
Querying Simbad for star: HD-34266
HD  34266
Querying Simbad for star: HD-344
HD    344
Querying Simbad for star: HD-3488
HD   3488
Querying Simbad for star: HD-36189
HD  36189
Querying Simbad for star: HD-36597
HD  36597
Querying Simbad for star: HD-36734
HD  36734
Querying Simbad for star: HD-36848
HD  36848
Querying Simbad for star: HD-37811
HD  37811
Querying Simbad for star: HD-38871
HD  38871
Querying Simbad for star: HD-3919
HD   3919
Querying Simbad for star: HD-39425
HD  39425
Querying Simbad for star: HD-39640
HD  39640
Querying Simbad for star: HD-40176
HD  40176
Querying Simbad for star: HD-4211
HD   4211
Querying Simbad for star: HD-42556
HD  42556
Querying Simbad for star: HD-43785
HD  43785
Querying Simbad for star: HD-4398
HD   4398
Querying Simbad for star: HD-46116
HD  46116
Querying Simbad for star: HD-46415
HD  46415
Querying Simbad for star: HD-46568
HD  46568
Querying Simbad for star: HD-47001
HD  47001
Querying Simbad for star: HD-4737
HD   4737
Querying Simbad for star: HD-47536
HD  47536
Querying Simbad for star: HD-47910
HD  47910
Querying Simbad for star: HD-49947
HD  49947
Querying Simbad for star: HD-5722
HD   5722
Querying Simbad for star: HD-59411
HD  59411
Querying Simbad for star: HD-59894
HD  59894
Querying Simbad for star: HD-60574
HD  60574
Querying Simbad for star: HD-6192
HD   6192
Querying Simbad for star: HD-61935
HD  61935
Querying Simbad for star: HD-62412
HD  62412
Querying Simbad for star: HD-6245
HD   6245
Querying Simbad for star: HD-62897
HD  62897
Querying Simbad for star: HD-62902
HD  62902
Querying Simbad for star: HD-62943
HD  62943
Querying Simbad for star: HD-63295
HD  63295
Querying Simbad for star: HD-63697
HD  63697
Querying Simbad for star: HD-64152
HD  64152
Querying Simbad for star: HD-64181
HD  64181
Querying Simbad for star: HD-6559
HD   6559
Querying Simbad for star: HD-65638
HD  65638
Querying Simbad for star: HD-65695
HD  65695
Querying Simbad for star: HD-67364
HD  67364
Querying Simbad for star: HD-67977
HD  67977
Querying Simbad for star: HD-67990
HD  67990
Querying Simbad for star: HD-68290
HD  68290A
Querying Simbad for star: HD-7082
HD   7082
Querying Simbad for star: HD-70982
HD  70982
Querying Simbad for star: HD-71863
HD  71863
Querying Simbad for star: HD-72650
HD  72650
Querying Simbad for star: HD-73468
HD  73468
Querying Simbad for star: HD-73665-Praes

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'HD 73665-Praes' this identifier has an incorrect format for catalog: 	HD : Henry Draper [astroquery.simbad.core]

Failed to query Simbad for star: HD 73665-Praes
Querying Simbad for star: HD-73710-Praes

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'HD 73710-Praes' this identifier has an incorrect format for catalog: 	HD : Henry Draper [astroquery.simbad.core]

Failed to query Simbad for star: HD 73710-Praes
Querying Simbad for star: HD-73887
HD  73887
Querying Simbad for star: HD-73898
HD  73898
Querying Simbad for star: HD-74622
HD  74622
Querying Simbad for star: HD-74772
HD  74772
Querying Simbad for star: HD-75168
HD  75168
Querying Simbad for star: HD-77087
HD  77087
Querying Simbad for star: HD-770
HD    770
Querying Simbad for star: HD-78004
HD  78004
Querying Simbad for star: HD-78632
HD  78632
Querying Simbad for star: HD-79917
HD  79917
Querying Simbad for star: HD-81101
HD  81101
Querying Simbad for star: HD-81169
HD  81169
Querying Simbad for star: HD-82347
HD  82347
Querying Simbad for star: HD-82350
HD  82350
Querying Simbad for star: HD-82514
HD  82514
Querying Simbad for star: HD-82734
HD  82734
Querying Simbad for star: HD-83441
HD  83441
Querying Simbad for star: HD-85250
HD  85250
Querying Simbad for star: HD-85444
HD  85444
Querying Simbad for star: HD-8705
HD   8705
Querying Simbad for star: HD-88323
HD  88323
Querying Simbad for star: HD-88836
HD  88836
Querying Simbad for star: HD-90518
HD  90518
Querying Simbad for star: HD-90957
HD  90957
Querying Simbad for star: HD-91437
HD  91437
Querying Simbad for star: HD-93257
HD  93257
Querying Simbad for star: HD-9362
HD   9362
Querying Simbad for star: HD-93813
HD  93813
Querying Simbad for star: HD-96407
HD  96407
Querying Simbad for star: HD-96566
HD  96566
Querying Simbad for star: HD-97344
HD  97344
Querying Simbad for star: HD-9742
HD   9742
Querying Simbad for star: HD-98430
HD  98430
Querying Simbad for star: HD-99167
HD  99167
Querying Simbad for star: HD-99322
HD  99322
Querying Simbad for star: HD005891
HD   5891
Querying Simbad for star: HD100655
HD 100655
Querying Simbad for star: HD10142
HD  10142
Querying Simbad for star: HD102272
HD 102272
Querying Simbad for star: HD107383_11Com

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'HD107383 11Com' this identifier has an incorrect format for catalog: 	HD : Henry Draper [astroquery.simbad.core]

Failed to query Simbad for star: HD107383_11Com
Querying Simbad for star: HD110829
HD 110829
Querying Simbad for star: HD113226
HD 113226
Querying Simbad for star: HD115319
HD 115319
Querying Simbad for star: HD11977
HD  11977
Querying Simbad for star: HD12055
HD  12055
Querying Simbad for star: HD121416
HD 121416
Querying Simbad for star: HD12477
HD  12477
Querying Simbad for star: HD125490
HD 125490
Querying Simbad for star: HD126035
HD 126035
Querying Simbad for star: HD13004
HD  13004
Querying Simbad for star: HD13423
HD  13423
Querying Simbad for star: HD1367
HD   1367
Querying Simbad for star: HD145936
HD 145936
Querying Simbad for star: HD145997
HD 145997
Querying Simbad for star: HD15220
HD  15220
Querying Simbad for star: HD15248
HD  15248
Querying Simbad for star: HD154619
HD 154619
Querying Simbad for star: HD15779
HD  15779
Querying Simbad for star: HD15799
HD  15799
Querying Simbad for star: HD162757
HD 162757
Querying Simbad for star: HD16522
HD  16522
Querying Simbad for star: HD1690
HD   1690
Querying Simbad for star: HD169370
HD 169370
Querying Simbad for star: HD169751
HD 169751
Querying Simbad for star: HD170031
HD 170031
Querying Simbad for star: HD170053
HD 170053
Querying Simbad for star: HD170174
HD 170174
Querying Simbad for star: HD170231
HD 170231
Querying Simbad for star: HD176704
HD 176704
Querying Simbad for star: HD177873
HD 177873
Querying Simbad for star: HD178484
HD 178484
Querying Simbad for star: HD184406
HD 184406
Querying Simbad for star: HD18784
HD  18784
Querying Simbad for star: HD190608
HD 190608
Querying Simbad for star: HD192836
HD 192836
Querying Simbad for star: HD198431
HD 198431
Querying Simbad for star: HD203050
HD 203050
Querying Simbad for star: HD206642
HD 206642
Querying Simbad for star: HD208000
HD 208000
Querying Simbad for star: HD209396
HD 209396
Querying Simbad for star: HD212943
HD 212943
Querying Simbad for star: HD217703
HD 217703
Querying Simbad for star: HD219449
HD 219449
Querying Simbad for star: HD219784
HD 219784
Querying Simbad for star: HD220572
HD 220572
Querying Simbad for star: HD221833
HD 221833
Querying Simbad for star: HD22798
HD  22798
Querying Simbad for star: HD26464
HD  26464
Querying Simbad for star: HD26967
HD  26967
Querying Simbad for star: HD35369
HD  35369
Querying Simbad for star: HD360
HD    360
Querying Simbad for star: HD36874
HD  36874
Querying Simbad for star: HD3750
HD   3750
Querying Simbad for star: HD38527
HD  38527
Querying Simbad for star: HD39523
HD  39523
Querying Simbad for star: HD40657
HD  40657
Querying Simbad for star: HD42089
HD  42089
Querying Simbad for star: HD45398
HD  45398
Querying Simbad for star: HD45415
HD  45415
Querying Simbad for star: HD47366
HD  47366
Querying Simbad for star: HD49429
HD  49429
Querying Simbad for star: HD49566
HD  49566
Querying Simbad for star: HD49608
HD  49608
Querying Simbad for star: HD52603
HD  52603
Querying Simbad for star: HD54131
HD  54131
Querying Simbad for star: HD54810
HD  54810
Querying Simbad for star: HD56160
HD  56160
Querying Simbad for star: HD5722
HD   5722
Querying Simbad for star: HD5891
HD   5891
Querying Simbad for star: HD60060
HD  60060
Querying Simbad for star: HD60341
HD  60341
Querying Simbad for star: HD6037
HD   6037
Querying Simbad for star: HD62412
HD  62412
Querying Simbad for star: HD63435
HD  63435
Querying Simbad for star: HD63798
HD  63798
Querying Simbad for star: HD63948
HD  63948
Querying Simbad for star: HD64152
HD  64152
Querying Simbad for star: HD64225
HD  64225
Querying Simbad for star: HD64967
HD  64967
Querying Simbad for star: HD68312
HD  68312
Querying Simbad for star: HD78050
HD  78050
Querying Simbad for star: HD79091
HD  79091
Querying Simbad for star: HD81101
HD  81101
Querying Simbad for star: HD8651
HD   8651
Querying Simbad for star: HD8733
HD   8733
Querying Simbad for star: HD8763
HD   8763
Querying Simbad for star: HD88399
HD  88399
Querying Simbad for star: HD90125
HD  90125
Querying Simbad for star: HD9362
HD   9362
Querying Simbad for star: HD94386
HD  94386
Querying Simbad for star: HD97605
HD  97605
Querying Simbad for star: HD_52483
HD  52483
Querying Simbad for star: HIP-64920

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'HIP-64920' this identifier has an incorrect format for catalog: 	HIP : Hipparcos catalogue [astroquery.simbad.core]

Failed to query Simbad for star: HIP-64920
Querying Simbad for star: HIP13684
HD  18202
Querying Simbad for star: HIP14838
HD  19787
Querying Simbad for star: HIP19641
HD  26546
Querying Simbad for star: HIP20226
HD  27370
Querying Simbad for star: HIP28485
HD  40726
Querying Simbad for star: HIP29526
HD  42911
Querying Simbad for star: HIP29575
HD  43023
Querying Simbad for star: HIP5364
HD   6805
Querying Simbad for star: HIP54769
HD  97443
Querying Simbad for star: HIP63242
HD 112410
Querying Simbad for star: HIP80242B

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : HIP 80242B [astroquery.simbad.core]

Failed to query Simbad for star: HIP80242B
Querying Simbad for star: HR-1654

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'HR-1654' this identifier has an incorrect format for catalog: 	HR : Harvard Revised photometry [astroquery.simbad.core]

Failed to query Simbad for star: HR-1654
Querying Simbad for star: HR7349
HD 181907
Querying Simbad for star: HR_3728
HD  81101
Querying Simbad for star: HR_3919
HD  85859
Querying Simbad for star: IC2714No.110

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No.110' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No.110
Querying Simbad for star: IC2714No.126

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No.126' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No.126
Querying Simbad for star: IC2714No.190

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No.190' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No.190
Querying Simbad for star: IC2714No.5

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No.5' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No.5
Querying Simbad for star: IC2714No121

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No121' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No121
Querying Simbad for star: IC2714No126

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No126' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No126
Querying Simbad for star: IC2714No190

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No190' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No190
Querying Simbad for star: IC2714No220

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No220' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No220
Querying Simbad for star: IC2714No5

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No5' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No5
Querying Simbad for star: IC2714No87

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC2714No87' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC2714No87
Querying Simbad for star: IC4651No10393

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No10393' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No10393
Querying Simbad for star: IC4651No11453

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No11453' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No11453
Querying Simbad for star: IC4651No14527

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No14527' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No14527
Querying Simbad for star: IC4651No7646

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No7646' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No7646
Querying Simbad for star: IC4651No8540

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No8540' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No8540
Querying Simbad for star: IC4651No9025

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No9025' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No9025
Querying Simbad for star: IC4651No9122

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No9122' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No9122
Querying Simbad for star: IC4651No9791

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4651No9791' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4651No9791
Querying Simbad for star: IC4756No28

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4756No28' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4756No28
Querying Simbad for star: IC4756No38

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4756No38' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4756No38
Querying Simbad for star: IC4756No52

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'IC4756No52' this identifier has an incorrect format for catalog: 	IC : Index Catalog [astroquery.simbad.core]

Failed to query Simbad for star: IC4756No52
Querying Simbad for star: NGC1662No.2

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC1662No.2' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC1662No.2
Querying Simbad for star: NGC2251No.35

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2251No.35' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2251No.35
Querying Simbad for star: NGC2360No119

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No119' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No119
Querying Simbad for star: NGC2360No50

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No50' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No50
Querying Simbad for star: NGC2360No66

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No66' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No66
Querying Simbad for star: NGC2360No79

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No79' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No79
Querying Simbad for star: NGC2360No7

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No7' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No7
Querying Simbad for star: NGC2360No85

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No85' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No85
Querying Simbad for star: NGC2360No86

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No86' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No86
Querying Simbad for star: NGC2360No89

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2360No89' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2360No89
Querying Simbad for star: NGC2423No3

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2423No3' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2423No3
Querying Simbad for star: NGC2447No85

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2447No85' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2447No85
Querying Simbad for star: NGC2477No4221

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2477No4221' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2477No4221
Querying Simbad for star: NGC2477No5094

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2477No5094' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2477No5094
Querying Simbad for star: NGC2477No5345

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2477No5345' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2477No5345
Querying Simbad for star: NGC2477No6058

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2477No6058' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2477No6058
Querying Simbad for star: NGC2539No229

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No229' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No229
Querying Simbad for star: NGC2539No246

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No246' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No246
Querying Simbad for star: NGC2539No251

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No251' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No251
Querying Simbad for star: NGC2539No317

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No317' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No317
Querying Simbad for star: NGC2539No346

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No346' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No346
Querying Simbad for star: NGC2539No447

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No447' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No447
Querying Simbad for star: NGC2539No463

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No463' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No463
Querying Simbad for star: NGC2539No502

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No502' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No502
Querying Simbad for star: NGC2539No652

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2539No652' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2539No652
Querying Simbad for star: NGC2567No114

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2567No114' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2567No114
Querying Simbad for star: NGC2567No37

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC2567No37' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC2567No37
Querying Simbad for star: NGC3114No223

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3114No223' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3114No223
Querying Simbad for star: NGC3532No.100

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No.100' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No.100
Querying Simbad for star: NGC3532No.122

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No.122' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No.122
Querying Simbad for star: NGC3532No.19

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No.19' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No.19
Querying Simbad for star: NGC3532No.596

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No.596' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No.596
Querying Simbad for star: NGC3532No100

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No100' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No100
Querying Simbad for star: NGC3532No122

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No122' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No122
Querying Simbad for star: NGC3532No19

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No19' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No19
Querying Simbad for star: NGC3532No596

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No596' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No596
Querying Simbad for star: NGC3532No649

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3532No649' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3532No649
Querying Simbad for star: NGC3680No26

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3680No26' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3680No26
Querying Simbad for star: NGC3680No41

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3680No41' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3680No41
Querying Simbad for star: NGC3680No53

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC3680No53' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC3680No53
Querying Simbad for star: NGC4349No127

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No127' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No127
Querying Simbad for star: NGC4349No168

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No168' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No168
Querying Simbad for star: NGC4349No174

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No174' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No174
Querying Simbad for star: NGC4349No53

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No53' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No53
Querying Simbad for star: NGC4349No5

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No5' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No5
Querying Simbad for star: NGC4349No9

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC4349No9' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC4349No9
Querying Simbad for star: NGC5822No.1

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.1' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.1
Querying Simbad for star: NGC5822No.240

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.240' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.240
Querying Simbad for star: NGC5822No.375

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.375' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.375
Querying Simbad for star: NGC5822No.443

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.443' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.443
Querying Simbad for star: NGC5822No.6

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.6' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.6
Querying Simbad for star: NGC5822No.8

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No.8' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No.8
Querying Simbad for star: NGC5822No375

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No375' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No375
Querying Simbad for star: NGC5822No8

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC5822No8' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC5822No8
Querying Simbad for star: NGC6281No3

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6281No3' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6281No3
Querying Simbad for star: NGC6281No4

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6281No4' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6281No4
Querying Simbad for star: NGC6494No46

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6494No46' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6494No46
Querying Simbad for star: NGC6494No48

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6494No48' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6494No48
Querying Simbad for star: NGC6494No6

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6494No6' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6494No6
Querying Simbad for star: NGC6633No100

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6633No100' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6633No100
Querying Simbad for star: NGC6633No106

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6633No106' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6633No106
Querying Simbad for star: NGC6705No160

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6705No160' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6705No160
Querying Simbad for star: NGC6705No1658

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6705No1658' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6705No1658
Querying Simbad for star: NGC6705No411

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6705No411' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6705No411
Querying Simbad for star: NGC6705No779

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6705No779' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6705No779
Querying Simbad for star: NGC6705No963

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NGC6705No963' this identifier has an incorrect format for catalog: 	NGC : catalogue NGC [astroquery.simbad.core]

Failed to query Simbad for star: NGC6705No963
Querying Simbad for star: NLTT17494
HD  54810
Querying Simbad for star: NLTT

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'NLTT' this identifier has an incorrect format for catalog: 	NLTT : Luyten recno in 1098, revised in 2003ApJ...582.1011S [astroquery.simbad.core]

Failed to query Simbad for star: NLTT
Querying Simbad for star: SAND1084

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'SAND1084' this identifier has an incorrect format for catalog: 	SAND : catalogue Sand [astroquery.simbad.core]

Failed to query Simbad for star: SAND1084
Querying Simbad for star: SAND978

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'SAND978' this identifier has an incorrect format for catalog: 	SAND : catalogue Sand [astroquery.simbad.core]

Failed to query Simbad for star: SAND978
Querying Simbad for star: TYC5434-3430-1
No HD ID found for star: TYC5434-3430-1
Querying Simbad for star: ZI-946_G5II

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): 'ZI-946 G5II': No known catalog could be found [astroquery.simbad.core]

Failed to query Simbad for star: ZI-946_G5II
Querying Simbad for star: alf_Mon
HD  61935
Querying Simbad for star: del_Crt
HD  98430
Querying Simbad for star: gam_Aps
HD 147675
Querying Simbad for star: lam_Pyx
HD  81169
Querying Simbad for star: pi_Hya
HD 123123
Querying Simbad for star: zet_Pyx
HD  73898

In [28]:
sarah_df = pd.DataFrame(sarah_hds)
sarah_df.to_csv('/data/misfit/benlowe/xshooter/p115/sarah/stars_HDs.csv', index=False)

# Getting the data loaded

Loading in the data, then combining

In [11]:
# Note - yong2013 is actually noris2013 data
yong2013_rvs = Table.read('/data/misfit/benlowe/xshooter/lit_abund_data/norris2013_rvs.fits')
jacobson2015_rvs = Table.read('/data/misfit/benlowe/xshooter/lit_abund_data/jacobson2015_rvs.fits')
marino2019_rvs = Table.read('/data/misfit/benlowe/xshooter/lit_abund_data/marino2019_rvs.fits')
yong2021_rvs = Table.read('/data/misfit/benlowe/xshooter/lit_abund_data/yong2021_rvs.fits')
cordoni2021_rvs = Table.read('/data/misfit/benlowe/xshooter/lit_abund_data/cordoni2021_rvs.fits')

# # display(yong2013_rvs)
# # display(jacobson2015_rvs)
# # display(marino2019_rvs)
# # display(yong2021_rvs)

# We only want the following columns: name and rv
yong2013_rvs = yong2013_rvs['Name', 'HRV'].to_pandas()
yong2013_rvs['Name'] = yong2013_rvs['Name'].str.decode('utf-8')  # Decode bytes to string

jacobson2015_rvs = jacobson2015_rvs['ID', 'RVel'].to_pandas()
jacobson2015_rvs['ID'] = jacobson2015_rvs['ID'].str.decode('utf-8')  # Decode bytes to string

marino2019_rvs = marino2019_rvs['Name', 'RV'].to_pandas()
marino2019_rvs['Name'] = marino2019_rvs['Name'].str.decode('utf-8')  # Decode bytes to string

yong2021_rvs = yong2021_rvs['SMSS', 'RV'].to_pandas()
yong2021_rvs['SMSS'] = yong2021_rvs['SMSS'].str.decode('utf-8')  # Decode bytes to string

cordoni2021_rvs = cordoni2021_rvs['SMSSJ', 'DatasetId'].to_pandas()
cordoni2021_rvs['SMSSJ'] = cordoni2021_rvs['SMSSJ'].str.decode('utf-8')  # Decode bytes to string
cordoni2021_rvs['DatasetId'] = cordoni2021_rvs['DatasetId'].str.decode('utf-8')  # Decode bytes to string

# # Updating column names to be consistent
# yong2013_rvs.rename_column('Name', 'star_id')
# yong2013_rvs.rename_column('HRV', 'rv')
# jacobson2015_rvs.rename_column('ID', 'star_id')
# jacobson2015_rvs.rename_column('RVel', 'rv')
# marino2019_rvs.rename_column('Name', 'star_id')
# marino2019_rvs.rename_column('RV', 'rv')
# yong2021_rvs.rename_column('SMSS', 'star_id')
# yong2021_rvs.rename_column('RV', 'rv')

# # # Combine all data into a single table
# # combined_rvs = vstack([yong2013_rvs, jacobson2015_rvs, marino2019_rvs, yong2021_rvs])
# # combined_rvs

WARNING: UnitsWarning: '"MMM/YYYY"' did not parse as fits unit: Invalid character at col 0 If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: UnitsWarning: '"YYYY/MMM/DD"' did not parse as fits unit: Invalid character at col 0 If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]
WARNING: VerifyWarning: It is strongly recommended that column names contain only upper and lower-case ASCII letters, digits, or underscores for maximum compatibility with other software (got '[Fe/H]'). [astropy.io.fits.column]
WARNING: UnitsWarning: '[K]' did not parse as fits unit: Invalid character at col 0 If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

For the left-over stars that had poor RVs from Jacobson+2015, replace their RVs with the Gaia DR3 values

In [30]:
# Loading in the left-over stars
leftover_stars = pd.read_csv('/data/misfit/benlowe/xshooter/lit_abund_data/jacobson2015_leftover_rvs.csv')
leftover_stars.dropna(inplace=True)
leftover_stars.rename(columns={'RV': 'rv', 'e_RV': 'rv_err'}, inplace=True)
display(leftover_stars)

# Loading in the literature combined data file
lit_comb_df = pd.read_csv('/data/misfit/benlowe/xshooter/lit_abund_data/all_lit_combined_data.csv')
lit_dist_df = pd.read_csv('/data/misfit/benlowe/xshooter/lit_abund_data/distances/all_dist_res.csv')

# Only keep the stars that are in the leftover_stars list
lit_comb_df = lit_comb_df[lit_comb_df['target_id'].isin(leftover_stars['star_id'])]
lit_dist_df = lit_dist_df[lit_dist_df['star_id'].isin(lit_comb_df['star_id'])]
# display(lit_comb_df)

# Updating the 'rv' and 'rv_err' columns in lit_comb_df with the values from leftover_stars
for i, row in lit_comb_df.iterrows():
    star_id = row['target_id']
    if star_id in leftover_stars['star_id'].values:
        rv_value = leftover_stars.loc[leftover_stars['star_id'] == star_id, 'rv'].values[0]
        rv_err_value = leftover_stars.loc[leftover_stars['star_id'] == star_id, 'rv_err'].values[0]
        lit_comb_df.at[i, 'rv'] = rv_value
        lit_comb_df.at[i, 'rv_err'] = rv_err_value

# Saving
lit_comb_df.to_csv('/data/misfit/benlowe/xshooter/lit_abund_data/all_lit_combined_data_leftover.csv', index=False)
lit_dist_df.to_csv('/data/misfit/benlowe/xshooter/lit_abund_data/distances/all_dist_res_leftover.csv', index=False)

                         star_id      rv  rv_err
0   Gaia DR3 4929544698191619968  250.70    1.67
1   Gaia DR3 4750437655640204672    2.51    4.15
2   Gaia DR3 5419890806457713664  119.76    1.63
3   Gaia DR3 5388294656205380992  318.25    1.51
4   Gaia DR3 5388282217980329472  198.63    2.39
5   Gaia DR3 6144678597923885824  302.00    0.72
6   Gaia DR3 6143888938119406208  327.47    1.71
7   Gaia DR3 3679882078898432256  293.96    4.64
8   Gaia DR3 6156127709422808320  172.82    4.35
9   Gaia DR3 6195800528494048128  182.55    2.42
10  Gaia DR3 6103881218977013120  392.56    3.45
11  Gaia DR3 6103098607217267712  -61.46   11.89
12  Gaia DR3 6235324054509365888  291.24    2.31
13  Gaia DR3 6250246214002836608   38.65    2.89
14  Gaia DR3 6040164554518124928  -79.85    1.83
15  Gaia DR3 6034664728651334144  242.85    1.53
16  Gaia DR3 6034710667615052160  153.64    4.00
17  Gaia DR3 4149252254126420992 -265.63    4.63
18  Gaia DR3 5954269464897669376   31.39    2.84
19  Gaia DR3 5954259504896609536  121.61    1.43
20  Gaia DR3 5956940109923924864  181.87    3.04
21  Gaia DR3 5956504467146272000  340.13    4.77
22  Gaia DR3 6730001413961209344  -79.63    4.01
24  Gaia DR3 6737084154322454784  -76.65    3.68
25  Gaia DR3 4075429355471279744   42.38    2.05
26  Gaia DR3 4081595661509060352 -100.03    4.43
27  Gaia DR3 4081235708886572160 -141.51    3.94
28  Gaia DR3 6660502280387982336  -48.87   11.60
29  Gaia DR3 6362553905072497792  450.80    1.28
30  Gaia DR3 6449260876643493888  357.81    1.27

# Extracting Gaia DR3 source IDs for stars

### Norris et al. (2013)
This has numerous naming schemes that need to be made aware of before putting into SIMBAD:

- **52972-5213-5047** This is an internal SDSS observation ID, structured as "MJD - Plug plate - fibre". Use that to get the RA and DEC coordinates for star, then to get UCAC4 ID, which can be queried on SIMBAD.
- **BS16545-089** This is part of the HK Survey. To Query, need to add "BPS" to the front, alongside spacing out "BS". As an example, this would be "BPS BS 16545-089".
- **CS30336-049** Again, this is part of the HK Survey. Like previously, need to add "BPS" to the front, alongside spacing out "CS". As an example, this would be "BPS CS 30336-049"
- **HE0049-3948** This is part of the HES Survey. To query, space the letters out from the numbers. As an example, this would be "HE 0049-3948"

First removing duplicaes, averaging RV values

In [4]:
yong2013_rvs = yong2013_rvs.groupby('Name', as_index=False).agg({
    'HRV': 'mean',       # Calculate average RV
})

display(yong2013_rvs)

              Name         HRV
0   52972-1213-507 -176.950000
1   53327-2044-515 -193.500000
2   53436-1996-093  -16.706667
3   54142-2667-094   43.400000
4   BS16545-089    -161.166667
5   CS30336-049    -236.633333
6   HE0049-3948     190.757143
7   HE0057-5959     375.323077
8   HE0102-1213      90.500000
9   HE0146-1548    -114.950000
10  HE0207-1423    -209.600000
11  HE0228-4047     124.672727
12  HE0231-6025     296.600000
13  HE0253-1331      30.566667
14  HE0314-1739      40.700000
15  HE0355-3728      82.000000
16  HE0945-1435     121.750000
17  HE1055+0104     324.600000
18  HE1116-0054     148.705263
19  HE1142-1422    -102.250000
20  HE1201-1512     238.025000
21  HE1204-0744     -49.700000
22  HE1207-3108      -3.700000
23  HE1320-2952     390.025000
24  HE1346-0427     -47.800000
25  HE1402-0523     -68.750000
26  HE1506-0113    -137.125000
27  HE2020-5228     -41.450000
28  HE2032-5633     260.400000
29  HE2047-4421      25.900000
30  HE2135-1924    -252.900000
31  HE2136-6030     156.450000
32  HE2139-5432     115.141176
33  HE2141-0726     -38.150000
34  HE2142-5656     103.400000
35  HE2202-4831      56.200000
36  HE2246-2410      -3.100000
37  HE2247-7400       5.700000

Separating out the different stars in Norris et al. (2013)

In [5]:
def get_sdss(star_id):
    """ Extracting UCAC4 ID from SDSS using plate-mjd-fibre format star ID.
    
    Parameters
    ----------
    star_id : str
        Star ID in plate-mjd-fibre format (e.g., '1234-56789-0123')
    
    Returns
    -------
    simbad_id : str
        Corresponding Simbad MAIN_ID for the star.
    """    
    # First getting the plate number, MJD and fibre number
    mjd = star_id.split('-')[0]
    plate_num = star_id.split('-')[1]
    fibre_num = star_id.split('-')[2]
    
    # Storing into Table
    sdss_target = Table({
    'plate': [plate_num], 
    'mjd': [mjd], 
    'fiberID': [fibre_num]
    })


    # We need to build a query to get RA/Dec for these objects.
    # The most efficient way for a list is to use an SQL query via astroquery.

    # 1. format the WHERE clause for multiple objects
    where_clauses = []
    for row in sdss_target:
        where_clauses.append(
            f"(plate={row['plate']} AND mjd={row['mjd']} AND fiberID={row['fiberID']})"
        )
    where_string = " OR ".join(where_clauses)

    # 2. Run the SQL query on SDSS Data Release 17 (or latest)
    query = f"""
    SELECT plate, mjd, fiberID, ra, dec
    FROM specObj
    WHERE {where_string}
    """

    sdss_results = SDSS.query_sql(query)
    
    # Extracting the RA and Dec values
    ra = sdss_results['ra']
    dec = sdss_results['dec']
    
    # Getting Simbad ID so to query
    c = SkyCoord(ra=ra*u.deg, dec=dec*u.deg)
    simbad_id = Simbad.query_region(c, radius=2 * u.arcsec)['MAIN_ID'][0]
    
    return simbad_id
    

# Running through Yong2013 data to get Gaia DR3 IDs
yong2013_dicts = []
for i, row in yong2013_rvs.iterrows():
    
    star = row['Name']
    rv = row['HRV']
    
    print(f"Running {i+1} of {len(yong2013_rvs)}")
    
    
    # --STEP 1: TIDY NOMENCLETURE--- $
    # Tidying SDSS stars
    # Need to first identify which stars are SDSS stars, then extract their Simbad IDs
    # by querying SDSS for their RA/Dec and then querying Simbad for their MAIN_IDs
    if star[0] == '5':
        
        # First extracting Simbad-compatible ID
        # For stars with no SDSS data, skip
        try:
            new_id = get_sdss(star)
            print(new_id)
        except TypeError:
            print(f"No SDSS data found for {star}")
            continue
            
            
    # Tidying up BPS BS stars
    elif star.startswith('BS'):
        new_id = f"BPS BS {star.split('BS')[1]}"
        star = f"BS {star.split('BS')[1]}"
            
    
    # Tidying up BPS CS stars
    elif star.startswith('CS'):
        new_id = f"BPS CS {star.split('CS')[1]}"
        star = f"CS {star.split('CS')[1]}"
        
        
    # Tidying up HE stars
    elif star.startswith('HE'):
        new_id = f"HE {star.split('HE')[1]}"
        star = f"HE {star.split('HE')[1]}"
    
    
    # ---STEP 2: QUERY SIMBAD TO GET GAIA DR3 ID--- $
    Simbad.add_votable_fields('ids')
    
    # Extracting all IDs associated with star on Simbad
    # If no data found, skip
    try:
        ids = Simbad.query_object(new_id)[0]
    except TypeError:
        print(f"No Simbad data found for {new_id}")
        continue
    
    # Extracting Gaia DR3 ID from list of IDs
    gaia_id = [s for s in str(ids['IDS']).split('|') if 'Gaia DR3' in s]
     
    # ---STEP 3: STORING RESULTS--- $
    if len(gaia_id) > 0:
        star_dict = {
            'catalog': 'Yong2013',
            'star_id': star,
            'gaia_id': gaia_id[0],
            'rv': rv
        }
        yong2013_dicts.append(star_dict)
    else:
        print(f"No Gaia DR3 ID found for {new_id}")
        continue
    
# Converting to DataFrame
yong2013_gaia_rvs = pd.DataFrame(yong2013_dicts)
display(yong2013_gaia_rvs)

Running 1 of 38
UCAC4 639-043606
Running 2 of 38
SDSS J014036.21+234458.1
Running 3 of 38
No SDSS data found for 53436-1996-093
Running 4 of 38
SDSS J085136.67+101803.1
Running 5 of 38
Running 6 of 38
Running 7 of 38
Running 8 of 38
Running 9 of 38
Running 10 of 38
Running 11 of 38
Running 12 of 38
No Gaia DR3 ID found for HE 0228-4047
Running 13 of 38
Running 14 of 38
Running 15 of 38
No Gaia DR3 ID found for HE 0314-1739
Running 16 of 38
No Gaia DR3 ID found for HE 0355-3728
Running 17 of 38
Running 18 of 38
No Gaia DR3 ID found for HE 1055+0104
Running 19 of 38
No Gaia DR3 ID found for HE 1116-0054
Running 20 of 38
Running 21 of 38
Running 22 of 38
Running 23 of 38
Running 24 of 38
Running 25 of 38
Running 26 of 38
Running 27 of 38
Running 28 of 38
No Gaia DR3 ID found for HE 2020-5228
Running 29 of 38
No Gaia DR3 ID found for HE 2032-5633
Running 30 of 38

WARNING: BlankResponseWarning: Warning: The script line number 3 raised an error (recorded in the `errors` attribute of the result table): Identifier not found in the database : HE 2047-4421 [astroquery.simbad.core]

No Simbad data found for HE 2047-4421
Running 31 of 38
Running 32 of 38
No Gaia DR3 ID found for HE 2136-6030
Running 33 of 38
Running 34 of 38
No Gaia DR3 ID found for HE 2141-0726
Running 35 of 38
Running 36 of 38
Running 37 of 38
No Gaia DR3 ID found for HE 2246-2410
Running 38 of 38

     catalog          star_id                       gaia_id          rv
0   Yong2013   52972-1213-507   Gaia DR3 811812182598263552 -176.950000
1   Yong2013   53327-2044-515   Gaia DR3 290930261314166528 -193.500000
2   Yong2013   54142-2667-094   Gaia DR3 598558225898219776   43.400000
3   Yong2013  BS 16545-089      Gaia DR3 760839819965612928 -161.166667
4   Yong2013  CS 30336-049     Gaia DR3 6795730493933072128 -236.633333
5   Yong2013  HE 0049-3948     Gaia DR3 4999601077986760320  190.757143
6   Yong2013  HE 0057-5959     Gaia DR3 4903905598859396480  375.323077
7   Yong2013  HE 0102-1213     Gaia DR3 2469299431456345984   90.500000
8   Yong2013  HE 0146-1548     Gaia DR3 5142929531133360768 -114.950000
9   Yong2013  HE 0207-1423     Gaia DR3 5148615002680748160 -209.600000
10  Yong2013  HE 0231-6025     Gaia DR3 4725830447971369856  296.600000
11  Yong2013  HE 0253-1331     Gaia DR3 5159232539793658112   30.566667
12  Yong2013  HE 0945-1435     Gaia DR3 5687210361230578176  121.750000
13  Yong2013  HE 1142-1422     Gaia DR3 3572694538597881600 -102.250000
14  Yong2013  HE 1201-1512     Gaia DR3 3568795670365205888  238.025000
15  Yong2013  HE 1204-0744     Gaia DR3 3594472015653451264  -49.700000
16  Yong2013  HE 1207-3108     Gaia DR3 3472600458906843392   -3.700000
17  Yong2013  HE 1320-2952     Gaia DR3 6182077008471951616  390.025000
18  Yong2013  HE 1346-0427     Gaia DR3 3632963817501130240  -47.800000
19  Yong2013  HE 1402-0523     Gaia DR3 3643850258222221824  -68.750000
20  Yong2013  HE 1506-0113     Gaia DR3 4418328965879435776 -137.125000
21  Yong2013  HE 2135-1924     Gaia DR3 6830623323639730176 -252.900000
22  Yong2013  HE 2139-5432     Gaia DR3 6461736966363075200  115.141176
23  Yong2013  HE 2142-5656     Gaia DR3 6460491700725230848  103.400000
24  Yong2013  HE 2202-4831     Gaia DR3 6560414664623817856   56.200000
25  Yong2013  HE 2247-7400     Gaia DR3 6381793915449034624    5.700000

### Jacobson et al. (2015)
All stars have SMSS IDs, which can be used to query SIMBAD directly

In [29]:
# Running through Jacobson2013 data to get Gaia DR3 IDs
jacobson2015_dicts = []
for i, row in jacobson2015_rvs.iterrows():
    
    star = row['ID']
    rv = row['RVel']
    
    print(f"Running {i+1} of {len(jacobson2015_rvs)}")
     
    # ---STEP 1: QUERY SIMBAD TO GET GAIA DR3 ID--- $
    Simbad.add_votable_fields('ids')
    
    ids = Simbad.query_object(star)[0]
    
    # Extracting all IDs associated with star on Simbad
    # If no data found, skip
    try:
        ids = Simbad.query_object(star)[0]
    except TypeError:
        print(f"No Simbad data found for {star}")
        continue
    
    # Extracting Gaia DR3 ID from list of IDs
    gaia_id = [s for s in str(ids['IDS']).split('|') if 'Gaia DR3' in s]
     
     
    # ---STEP 2: STORING RESULTS--- $
    if len(gaia_id) > 0:
        star_dict = {
            'catalog': 'Jacobson2015',
            'star_id': star,
            'gaia_id': gaia_id[0],
            'rv': rv
        }
        jacobson2015_dicts.append(star_dict)
    else:
        print(f"No Gaia DR3 ID found for {star}")
        continue
    
# Converting to DataFrame
jacobson2015_gaia_rvs = pd.DataFrame(jacobson2015_dicts)
display(jacobson2015_gaia_rvs)

Running 1 of 135
Running 2 of 135
Running 3 of 135
Running 4 of 135
Running 5 of 135
Running 6 of 135
Running 7 of 135
Running 8 of 135
Running 9 of 135
Running 10 of 135
Running 11 of 135
Running 12 of 135
Running 13 of 135
Running 14 of 135
Running 15 of 135
Running 16 of 135
Running 17 of 135
Running 18 of 135
Running 19 of 135
Running 20 of 135
Running 21 of 135
Running 22 of 135
Running 23 of 135
Running 24 of 135
Running 25 of 135
Running 26 of 135
Running 27 of 135
Running 28 of 135
Running 29 of 135
Running 30 of 135
Running 31 of 135
Running 32 of 135
Running 33 of 135
Running 34 of 135
Running 35 of 135
Running 36 of 135
Running 37 of 135
Running 38 of 135
Running 39 of 135
Running 40 of 135
Running 41 of 135
Running 42 of 135
Running 43 of 135
Running 44 of 135
Running 45 of 135
Running 46 of 135
Running 47 of 135
Running 48 of 135
Running 49 of 135
Running 50 of 135
Running 51 of 135
Running 52 of 135
Running 53 of 135
Running 54 of 135
Running 55 of 135
Running 56 of 135
Running 57 of 135
Running 58 of 135
Running 59 of 135
Running 60 of 135
Running 61 of 135
Running 62 of 135
Running 63 of 135
Running 64 of 135
Running 65 of 135
Running 66 of 135
Running 67 of 135
Running 68 of 135
Running 69 of 135
Running 70 of 135
Running 71 of 135
Running 72 of 135
Running 73 of 135
Running 74 of 135
Running 75 of 135
Running 76 of 135
Running 77 of 135
Running 78 of 135
Running 79 of 135
Running 80 of 135
Running 81 of 135
Running 82 of 135
Running 83 of 135
Running 84 of 135
Running 85 of 135
Running 86 of 135
Running 87 of 135
Running 88 of 135
Running 89 of 135
Running 90 of 135
Running 91 of 135
Running 92 of 135
Running 93 of 135
Running 94 of 135
Running 95 of 135
Running 96 of 135
Running 97 of 135
Running 98 of 135
Running 99 of 135
Running 100 of 135
Running 101 of 135
Running 102 of 135
Running 103 of 135
Running 104 of 135
Running 105 of 135
Running 106 of 135
Running 107 of 135
Running 108 of 135
Running 109 of 135
Running 110 of 135
Running 111 of 135
Running 112 of 135
Running 113 of 135
Running 114 of 135
Running 115 of 135
Running 116 of 135
Running 117 of 135
Running 118 of 135
Running 119 of 135
Running 120 of 135
Running 121 of 135
Running 122 of 135
Running 123 of 135
Running 124 of 135
Running 125 of 135
Running 126 of 135
Running 127 of 135
Running 128 of 135
Running 129 of 135
Running 130 of 135
Running 131 of 135
Running 132 of 135
Running 133 of 135
Running 134 of 135
Running 135 of 135

,catalog,star_id,gaia_id,rv
0,Jacobson2015,SMSS J000113.96-363337.9,Gaia DR3 2307996956788376704,243.3
1,Jacobson2015,SMSS J001039.86-525851.4,Gaia DR3 4972144279777499776,110.0
2,Jacobson2015,SMSS J001952.15-525803.0,Gaia DR3 4924443101677817984,154.8
3,Jacobson2015,SMSS J002148.06-471132.1,Gaia DR3 4977550544093082624,204.5
4,Jacobson2015,SMSS J003055.81-482011.3,Gaia DR3 4975489337747579136,109.3
...,...,...,...,...
130,Jacobson2015,SMSS J225851.25-265434.9,Gaia DR3 6610033116122218752,141.5
131,Jacobson2015,SMSS J230013.16-263511.0,Gaia DR3 6610068261839783680,-240.0
132,Jacobson2015,SMSS J230113.95-291458.2,Gaia DR3 6606312196975322112,185.3
133,Jacobson2015,2MASS J23203653-3637223,Gaia DR3 6551640110860357504,-82.5
134,Jacobson2015,2MASS J23261426-3719492,Gaia DR3 6550624269490355456,146.1

According to Cordoni et al. (2021), there are several stars that have incorrect radial velocity measurements from Jacobson et al. (2015). These stars had poor comparision with Gaia DR2 velocities, so they were dumped due to their extreme differences. We will therefore only use the stars used from Cordoni et al. (2021)

In [47]:
# Extracting stars with good RVs from Cordoni2021 data
stars_good_rvs = cordoni2021_rvs[cordoni2021_rvs['DatasetId'] == 'Jacobson+15'][['SMSSJ']]
stars_good_rvs['SMSSJ'] = 'SMSS J' + stars_good_rvs['SMSSJ']

# Running through Cordoni2021 data to get Gaia DR3 IDs
cordoni2021_dicts = []
for i, row in stars_good_rvs.iterrows():
    
    star = row['SMSSJ']
    
    print(f"Running {i+1} of {len(stars_good_rvs)}")
     
    # ---STEP 1: QUERY SIMBAD TO GET GAIA DR3 ID--- $
    Simbad.add_votable_fields('ids')
    
    ids = Simbad.query_object(star)[0]
    
    # Extracting all IDs associated with star on Simbad
    # If no data found, skip
    try:
        ids = Simbad.query_object(star)[0]
    except TypeError:
        print(f"No Simbad data found for {star}")
        continue
    
    # Extracting Gaia DR3 ID from list of IDs
    gaia_id = [s for s in str(ids['IDS']).split('|') if 'Gaia DR3' in s]
     
     
    # ---STEP 2: STORING RESULTS--- $
    if len(gaia_id) > 0:
        star_dict = {
            'catalog': 'cordoni2021',
            'star_id': star,
            'gaia_id': gaia_id[0]
        }
        cordoni2021_dicts.append(star_dict)
    else:
        print(f"No Gaia DR3 ID found for {star}")
        continue
    
# Converting to DataFrame
cordoni2021_gaia_rvs = pd.DataFrame(cordoni2021_dicts)
display(cordoni2021_gaia_rvs)

Running 334 of 91
Running 335 of 91
Running 336 of 91
Running 337 of 91
Running 338 of 91
Running 339 of 91
Running 340 of 91
Running 341 of 91
Running 342 of 91
Running 343 of 91
Running 344 of 91
Running 345 of 91
Running 346 of 91
Running 347 of 91
Running 348 of 91
Running 349 of 91
Running 350 of 91
Running 351 of 91
Running 352 of 91
Running 353 of 91
Running 354 of 91
Running 355 of 91
Running 356 of 91
Running 357 of 91
Running 358 of 91
Running 359 of 91
Running 360 of 91
Running 361 of 91
Running 362 of 91
Running 363 of 91
Running 364 of 91
Running 365 of 91
Running 366 of 91
Running 367 of 91
Running 368 of 91
Running 369 of 91
Running 370 of 91
Running 371 of 91
Running 372 of 91
Running 373 of 91
Running 374 of 91
Running 375 of 91
Running 376 of 91
Running 377 of 91
Running 378 of 91
Running 379 of 91
Running 380 of 91
Running 381 of 91
Running 382 of 91
Running 383 of 91
Running 384 of 91
Running 385 of 91
Running 386 of 91
Running 387 of 91
Running 388 of 91
Running 389 of 91
Running 390 of 91
Running 391 of 91
Running 392 of 91
Running 393 of 91
Running 394 of 91
Running 395 of 91
Running 396 of 91
Running 397 of 91
Running 398 of 91
Running 399 of 91
Running 400 of 91
Running 401 of 91
Running 402 of 91
Running 403 of 91
Running 404 of 91
Running 405 of 91
Running 406 of 91
Running 407 of 91
Running 408 of 91
Running 409 of 91
Running 410 of 91
Running 411 of 91
Running 412 of 91
Running 413 of 91
Running 414 of 91
Running 415 of 91
Running 416 of 91
Running 417 of 91
Running 418 of 91
Running 419 of 91
Running 420 of 91
Running 421 of 91
Running 422 of 91
Running 423 of 91
Running 424 of 91

        catalog                    star_id                       gaia_id
0   cordoni2021  SMSS J000113.97-363337.8   Gaia DR3 2307996956788376704
1   cordoni2021  SMSS J001039.85-525851.4   Gaia DR3 4972144279777499776
2   cordoni2021  SMSS J001952.14-525802.9   Gaia DR3 4924443101677817984
3   cordoni2021  SMSS J002148.06-471132.1   Gaia DR3 4977550544093082624
4   cordoni2021  SMSS J003055.81-482010.9   Gaia DR3 4975489337747579136
..          ...                        ...                           ...
86  cordoni2021  SMSS J225851.25-265434.7   Gaia DR3 6610033116122218752
87  cordoni2021  SMSS J230013.15-263511.1   Gaia DR3 6610068261839783680
88  cordoni2021  SMSS J230113.95-291458.0   Gaia DR3 6606312196975322112
89  cordoni2021  SMSS J232036.19-363729.4   Gaia DR3 6551640115155355008
90  cordoni2021  SMSS J232614.26-371949.1   Gaia DR3 6550624269490355456

[91 rows x 3 columns]

In [67]:
cordoni2021_gaia_rvs.to_csv('/data/misfit/benlowe/xshooter/lit_abund_data/cordoni2021_gaia_ids.csv', index=False)

### Marino et al. (2019)
All stars have SMSS IDs, which can be used to query SIMBAD directly

In [44]:
# Running through Jacobson2013 data to get Gaia DR3 IDs
marino2019_dicts = []
for i, row in marino2019_rvs.iterrows():
    
    star = row['Name']
    rv = row['RV']
    
    print(f"Running {i+1} of {len(marino2019_rvs)}")
     
     
    # ---STEP 1: QUERY SIMBAD TO GET GAIA DR3 ID--- $
    Simbad.add_votable_fields('ids')
    
    # Extracting all IDs associated with star on Simbad
    # If no data found, skip
    try:
        ids = Simbad.query_object(new_id)[0]
    except TypeError:
        print(f"No Simbad data found for {new_id}")
        continue
    
    # Extracting Gaia DR3 ID from list of IDs
    gaia_id = [s for s in str(ids['IDS']).split('|') if 'Gaia DR3' in s]
     
     
    # ---STEP 2: STORING RESULTS--- $
    if len(gaia_id) > 0:
        star_dict = {
            'catalog': 'Marino2019',
            'star_id': star,
            'gaia_id': gaia_id[0],
            'rv': rv
        }
        marino2019_dicts.append(star_dict)
    else:
        print(f"No Gaia DR3 ID found for {new_id}")
        continue
    
# Converting to DataFrame
marino2019_gaia_rvs = pd.DataFrame(marino2019_dicts)
display(marino2019_gaia_rvs)

Running 1 of 17
Running 2 of 17
Running 3 of 17
Running 4 of 17
Running 5 of 17
Running 6 of 17
Running 7 of 17
Running 8 of 17
Running 9 of 17
Running 10 of 17
Running 11 of 17
Running 12 of 17
Running 13 of 17
Running 14 of 17
Running 15 of 17
Running 16 of 17
Running 17 of 17

       catalog                   star_id                       gaia_id     rv
0   Marino2019  SMSS J202059.17-043447.0  Gaia DR3 6381793915449034624 -190.7
1   Marino2019  SMSS J202400.03-024445.9  Gaia DR3 6381793915449034624 -133.8
2   Marino2019  SMSS J202601.44-033002.5  Gaia DR3 6381793915449034624 -149.5
3   Marino2019  SMSS J202659.41-031149.2  Gaia DR3 6381793915449034624 -199.1
4   Marino2019  SMSS J204654.92-020409.2  Gaia DR3 6381793915449034624 -451.2
5   Marino2019  SMSS J211657.83-012517.5  Gaia DR3 6381793915449034624 -155.4
6   Marino2019  SMSS J212001.71-001158.6  Gaia DR3 6381793915449034624 -350.2
7   Marino2019  SMSS J212113.63-005132.2  Gaia DR3 6381793915449034624   33.9
8   Marino2019  SMSS J212217.52-295552.7  Gaia DR3 6381793915449034624  200.8
9   Marino2019  SMSS J220514.10-013407.6  Gaia DR3 6381793915449034624 -199.2
10  Marino2019  SMSS J220535.05-004403.6  Gaia DR3 6381793915449034624  -62.2
11  Marino2019  SMSS J221334.13-072604.1  Gaia DR3 6381793915449034624 -392.7
12  Marino2019  SMSS J222349.48-114751.1  Gaia DR3 6381793915449034624 -367.1
13  Marino2019  SMSS J225336.83-270435.4  Gaia DR3 6381793915449034624  116.6
14  Marino2019  SMSS J230306.22-041621.8  Gaia DR3 6381793915449034624 -244.6
15  Marino2019  SMSS J010839.58-285701.5  Gaia DR3 6381793915449034624  144.3
16  Marino2019  SMSS J034249.52-284215.8  Gaia DR3 6381793915449034624  157.2

### Yong et al. (2021)
All stars have SMSS IDs, which can be used to query SIMBAD directly

In [15]:
# Running through Jacobson2013 data to get Gaia DR3 IDs
yong2021_dicts = []
for i, row in yong2021_rvs.iterrows():
    
    star = row['SMSS']
    rv = row['RV']
    
    # print(f"Running {i+1} of {len(yong2021_rvs)}")
     
     
    # ---STEP 1: FIX STAR NAME--- #
    # Fixing SMSS names to match Simbad format
    # (need 'SMSS' added to front of name)
    new_id = star.replace('J', 'SMSS J')
    print(new_id)
     
#     # ---STEP 2: QUERY SIMBAD TO GET GAIA DR3 ID--- $
#     Simbad.add_votable_fields('ids')
    
#     # Extracting all IDs associated with star on Simbad
#     # If no data found, skip
#     try:
#         ids = Simbad.query_object(new_id)[0]
#     except TypeError:
#         print(f"No Simbad data found for {new_id}")
#         continue
    
#     # Extracting Gaia DR3 ID from list of IDs
#     gaia_id = [s for s in str(ids['IDS']).split('|') if 'Gaia DR3' in s]
     
     
#     # ---STEP 3: STORING RESULTS--- $
#     if len(gaia_id) > 0:
#         star_dict = {
#             'catalog': 'yong2021',
#             'star_id': star,
#             'gaia_id': gaia_id[0],
#             'rv': rv
#         }
#         yong2021_dicts.append(star_dict)
#     else:
#         print(f"No Gaia DR3 ID found for {new_id}")
#         continue
    
# # Converting to DataFrame
# yong2021_gaia_rvs = pd.DataFrame(yong2021_dicts)
# display(yong2021_gaia_rvs)

SMSS J001604.23-024105.0
SMSS J005420.96-844117.0
SMSS J011126.27-495048.4
SMSS J020050.19-465735.2
SMSS J024246.96-470353.6
SMSS J030245.60-281454.0
SMSS J030258.53-284326.9
SMSS J030428.44-340604.8
SMSS J030634.26-750133.3
SMSS J030740.92-610018.8
SMSS J030853.27-700140.1
SMSS J030922.03-544038.1
SMSS J031703.94-374047.2
SMSS J034504.76-724732.2
SMSS J034749.80-751351.7
SMSS J043522.14-470449.0
SMSS J043800.94-831932.8
SMSS J044147.05-484842.9
SMSS J050247.62-642915.9
SMSS J051729.79-425336.0
SMSS J052313.34-621822.5
SMSS J053721.56-244251.5
SMSS J053721.56-244251.5
SMSS J054650.97-471407.9
SMSS J054903.50-594655.4
SMSS J054913.80-453904.0
SMSS J062208.92-675713.1
SMSS J062445.32-623003.7
SMSS J063627.00-551633.2
SMSS J072146.02-835759.7
SMSS J074358.63-612711.4
SMSS J074828.02-620137.9
SMSS J081112.13-054237.7
SMSS J081627.99-055913.3
SMSS J082303.10-115033.0
SMSS J083055.45-734903.6
SMSS J084327.83-141513.3
SMSS J084457.17-264325.4
SMSS J085210.25-761250.2
SMSS J085540.04-234607.3
SMSS J090151.44-621037.5
SMSS J091043.10-144418.5
SMSS J091117.11-264637.1
SMSS J092215.80-712521.3
SMSS J092357.06-203851.2
SMSS J093047.12-235727.7
SMSS J093524.93-715506.5
SMSS J093524.93-715506.5
SMSS J095211.09-185713.7
SMSS J095211.09-185713.7
SMSS J095246.98-085554.0
SMSS J095456.70-002141.5
SMSS J095456.70-002141.5
SMSS J095534.44-190405.2
SMSS J095803.36-322749.6
SMSS J102410.14-082802.8
SMSS J102410.14-082802.8
SMSS J102731.70-411130.5
SMSS J103235.57-131520.2
SMSS J103819.28-284817.9
SMSS J105512.06-215551.8
SMSS J110901.23+075441.7
SMSS J111201.72-221207.7
SMSS J112810.03-064656.2
SMSS J113545.64+022820.4
SMSS J115906.91-261050.6
SMSS J120218.07-400934.9
SMSS J120509.03-295940.6
SMSS J120638.24-291441.1
SMSS J120638.24-291441.1
SMSS J121615.75-281249.1
SMSS J121709.12-272103.6
SMSS J121709.12-272103.6
SMSS J121846.49-161050.7
SMSS J122207.37-252124.5
SMSS J123608.04-343528.5
SMSS J125117.10-421643.2
SMSS J125142.79-424304.4
SMSS J125704.60-105407.2
SMSS J133308.90-465407.9
SMSS J134416.02-235714.9
SMSS J135100.02-430836.3
SMSS J135544.04-375045.4
SMSS J142445.33-254247.0
SMSS J143511.34-420326.4
SMSS J143531.93-471904.2
SMSS J143626.75-363115.5
SMSS J144711.50-195545.8
SMSS J144749.23-330859.5
SMSS J145536.24-340538.2
SMSS J145738.47-261358.7
SMSS J145902.35-091610.5
SMSS J151044.04-395653.6
SMSS J151056.54-793923.8
SMSS J152349.60-222540.5
SMSS J153601.77-013125.2
SMSS J154332.59-300038.2
SMSS J154340.00-831819.5
SMSS J154521.54-102047.4
SMSS J154634.19-081030.9
SMSS J154917.11-642300.6
SMSS J155730.10-293922.6
SMSS J160624.86-253008.6
SMSS J162526.57-762949.8
SMSS J163040.08-715639.1
SMSS J163800.01-794316.3
SMSS J164423.20-650458.8
SMSS J164707.10-001155.5
SMSS J164757.15-651940.6
SMSS J165244.66-271205.2
SMSS J165501.84-664110.7
SMSS J165512.00-725554.9
SMSS J170133.47-651115.6
SMSS J170359.88-670954.4
SMSS J171221.51-584828.1
SMSS J172313.82-602320.6
SMSS J172604.29-590656.1
SMSS J172626.92-575927.9
SMSS J173002.48-532901.2
SMSS J174742.66-571315.5
SMSS J175134.00-595225.3
SMSS J175342.48-703556.0
SMSS J180105.44-732703.7
SMSS J180500.16-464212.4
SMSS J181200.10-463148.8
SMSS J182735.70-341930.9
SMSS J182845.79-354022.8
SMSS J183125.34-482205.3
SMSS J183310.29-645031.0
SMSS J184807.37-553441.0
SMSS J184853.07-550646.9
SMSS J185358.63-555400.1
SMSS J185358.63-555400.1
SMSS J185624.55-421733.7
SMSS J185652.03-563838.9
SMSS J185753.23-493341.2
SMSS J190415.62-602628.5
SMSS J190508.31-581843.9
SMSS J190556.70-454724.2
SMSS J190836.24-401623.5
SMSS J193613.62-354643.6
SMSS J194549.85-232502.6
SMSS J200154.32-102845.7
SMSS J200322.54-114203.3
SMSS J202654.59-004726.4
SMSS J202654.59-004726.4
SMSS J202909.78-400236.5
SMSS J203416.25-295108.3
SMSS J205001.91-661329.7
SMSS J210918.48-363547.1
SMSS J211747.91-404512.2
SMSS J212110.47-611758.9
SMSS J212847.25-611328.5
SMSS J213402.81-622421.1
SMSS J214226.98-712419.0
SMSS J214642.09-312521.7
SMSS J214716.16-081546.9
SMSS J215106.86-202548.2
SMSS J215842.28-202915.8
SMSS J222217.73-341606.1
SMSS J222323.36-482451.3
SMSS J224145.62-064643.0
SMSS J230525.31-213807.0
SMSS J230702.22-693718.5
SMSS J232121.57-160505.4
SMSS J234805.23-514821.0

## Combining all datasets

In [3]:
combined_gaia_rvs = pd.concat([yong2013_gaia_rvs, jacobson2015_gaia_rvs, marino2019_gaia_rvs, yong2021_gaia_rvs], ignore_index=True)
combined_gaia_rvs['gaia_id'] = combined_gaia_rvs['gaia_id'].str.replace('Gaia DR3 ', '')
display(combined_gaia_rvs)

# According to Cordoni et al. (2021), some stars from Jacobson

# combined_gaia_rvs.to_csv('/data/misfit/benlowe/xshooter/p113/lit_abund_data/all_lit_rvs.csv', index=False)

NameError: name 'yong2013_gaia_rvs' is not defined

# Getting Gaia DR3 values for targets

Running the following ADQL query in TOPCAT

SELECT gaia.*

FROM gaia.gaia_source_lite AS gaia

JOIN TAP_UPLOAD.t1 as up

ON gaia.source_id = up.gaia_id

In [27]:
gaia_ids

      catalog              star_id            source_id          rv
0    yong2013       52972-1213-507   811812182598263552 -176.950000
1    yong2013       53327-2044-515   290930261314166528 -193.500000
2    yong2013       54142-2667-094   598558225898219776   43.400000
3    yong2013      BS 16545-089      760839819965612928 -161.166667
4    yong2013      CS 30336-049     6795730493933072128 -236.633333
..        ...                  ...                  ...         ...
333  yong2021  J224145.62-064643.0  2623363791014198656 -201.600000
334  yong2021  J230525.31-213807.0  2398202677437168384  -15.700000
335  yong2021  J230702.22-693718.5  6384594749521894400  173.900000
336  yong2021  J232121.57-160505.4  2406023396270909440  -39.100000
337  yong2021  J234805.23-514821.0  6521746111985049344  -93.900000

[338 rows x 4 columns]

In [4]:
gaia_ids = pd.read_csv('/data/misfit/benlowe/xshooter/lit_abund_data/all_lit_rvs.csv')
gaia_ids.rename(columns={'gaia_id': 'source_id'}, inplace=True)

new_gaia_df = pd.read_csv('/data/misfit/benlowe/xshooter/lit_abund_data/all_lit_gaiadr3_v2.csv')

t = pd.merge(gaia_ids[['catalog', 'star_id', 'source_id']], new_gaia_df, on='source_id', how='left')
t = t.drop_duplicates('star_id')
# t.to_csv('/data/misfit/benlowe/xshooter/lit_abund_data/all_lit_gaiadr3_final.csv', index=False)


t

# final = []
# for i, row in gaia_ids.iterrows():
#     source_id = row['source_id']
    
#     # Finding matching row in new_gaia_df
#     match = new_gaia_df[new_gaia_df['source_id'] == source_id]
#     final.append(match)

# final_df = pd.concat(final, ignore_index=True)
# display(final_df.drop_duplicates())

,catalog,star_id,source_id,random_index,ra,dec,parallax,parallax_error,parallax_over_error,pmra,...,ebpminrp_gspphot,target_id,target_ra,target_dec,target_parallax,target_pm_ra,target_pm_dec,target_radial_velocity,epoch,target_separation (deg)
0,yong2013,52972-1213-507,811812182598263552,730540375,139.707938,37.740593,0.468856,0.039756,11.793310,-5.860822,...,0.0115,Gaia DR3 811812182598263552,139.707938,37.740593,0.4689,-5.8608,-33.2725,0.0000,2016.0,0.000000e+00
1,yong2013,53327-2044-515,290930261314166528,1215239180,25.150925,23.749406,1.066217,0.036955,28.851522,0.972496,...,0.2907,Gaia DR3 290930261314166528,25.150925,23.749406,1.0662,0.9725,-21.5905,0.0000,2016.0,0.000000e+00
2,yong2013,54142-2667-094,598558225898219776,772626430,132.902825,10.300841,0.422213,0.028656,14.734057,-8.773143,...,0.1108,Gaia DR3 598558225898219776,132.902825,10.300841,0.4222,-8.7731,-17.1661,0.0000,2016.0,1.776357e-15
3,yong2013,BS 16545-089,760839819965612928,344569189,171.114717,36.841186,0.644339,0.023748,27.132257,10.309770,...,0.0405,Gaia DR3 760839819965612928,171.114717,36.841186,0.6443,10.3098,-34.1174,0.0000,2016.0,0.000000e+00
4,yong2013,CS 30336-049,6795730493933072128,60677280,311.348047,-28.710012,0.062969,0.017374,3.624422,-1.727017,...,NaN,Gaia DR3 6795730493933072128,311.348047,-28.710012,0.0630,-1.7270,-8.1800,-235.8673,2016.0,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
391,yong2021,J224145.62-064643.0,2623363791014198656,990092424,340.440108,-6.778676,0.075457,0.018667,4.042358,1.869163,...,NaN,Gaia DR3 2623363791014198656,340.440108,-6.778676,0.0755,1.8692,-2.8984,-207.4769,2016.0,8.881784e-16
392,yong2021,J230525.31-213807.0,2398202677437168384,779426047,346.355546,-21.635311,0.286466,0.012346,23.202960,-1.075391,...,NaN,Gaia DR3 2398202677437168384,346.355546,-21.635311,0.2865,-1.0754,-15.1677,-17.3665,2016.0,0.000000e+00
393,yong2021,J230702.22-693718.5,6384594749521894400,286939962,346.759342,-69.621844,0.052283,0.015166,3.447462,1.060945,...,NaN,Gaia DR3 6384594749521894400,346.759342,-69.621844,0.0523,1.0609,-5.9018,153.2275,2016.0,0.000000e+00
394,yong2021,J232121.57-160505.4,2406023396270909440,605784975,350.339926,-16.084881,0.456265,0.013901,32.823170,17.221111,...,NaN,Gaia DR3 2406023396270909440,350.339926,-16.084881,0.4563,17.2211,3.4440,-40.4604,2016.0,0.000000e+00
395,yong2021,J234805.23-514821.0,6521746111985049344,858625723,357.021884,-51.805870,0.067929,0.022413,3.030734,0.159120,...,NaN,Gaia DR3 6521746111985049344,357.021884,-51.805870,0.0679,0.1591,-3.3286,0.0000,2016.0,3.514787e-14

# Getting errors for the literature data

For Yong+2021

In [11]:
yong2021_errs = fits.open('/data/misfit/benlowe/xshooter/lit_abund_data/yong2021_abunds_errors.fits')
yong2021_errs[1].data

ValueError: could not convert string to float: b' --- '; the header may be missing the necessary TNULL4 keyword or the table contains invalid data